# site settings
title:"Cardinal"
subtitle:"Welcome！"
email:"217010022@link.cuhk.edu.cn"
description:u"请多多指教，有失远迎，还请包含"
baseurl:"/blog" # the subpath of your site, e.g. /blog
url:"www.whosedaddy.github.io"# the base hostname & protocol for your site
author:"Sunao"
street_address:u"云端大道"
city:u"深圳"
state:u"广东"
zip_code:431600
country:u"中国"
phone: 17603062105

# homepage tiles
tiles-source: "posts" # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:https://github.com/whosedaddy
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: http://www.linkedin.com/in/sun-ao-a79496148/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: cmdmarkdown

sass:
  style: compressed
